### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by Slach** [knight42/kubectl-blame#13]
Hello thanks for great plugin
could you add windows support?

**Comment by knight42** [comment]
Sure thing!

**Comment by knight42** [comment]
@Slach I am waiting for approval for https://github.com/kubernetes-sigs/krew-index/pull/3098. If you don't mind, you could download the binary from the release page https://github.com/knight42/kubectl-blame/releases/tag/v0.0.11.

**Comment by knight42** [comment]
@Slach Hi, you could try to install this plugin on Windows now: `kubectl krew install blame`. Please feel free to reopen this issue if any problem occurs.

**Comment by Slach** [comment]
works perfectly, thanks a lot
