### ISSUE TITLE
Additional Steps Needed For Krew Submission

### ISSUE THREAD

**Issue by shpwrck** [knight42/kubectl-blame#2]
I submitted a Krew plugin manifest for this plugin, but it still needs some slight modifications.
https://github.com/kubernetes-sigs/krew-index/pull/1008

1) I wanted to make your approval trackable.
2) I wanted to let you control how you handle the [auth request](https://github.com/kubernetes-sigs/krew-index/pull/1008#issuecomment-773653362)
3) I wanted to give you visibility into the Caveats/Description etc.

**Comment by knight42** [comment]
@shpwrck Hi! Thanks for your effort! I was on vacation last few days.

The authentication plugins have been imported now: https://github.com/knight42/kubectl-blame/commit/27ad579f9d6c72c3dc2e5ae622ee4c3fa2236ab3 and I have made a new release: https://github.com/knight42/kubectl-blame/releases/tag/v0.0.4

**Comment by knight42** [comment]
This plugin could be installed by krew now: `kubectl krew install blame`. Thanks for your effort!
