### ISSUE TITLE
allow reading a file / stdin and not only k8s resources

### ISSUE THREAD

**Issue by georgettica** [knight42/kubectl-blame#6]
I found this problematic where I found a resource with `.metadata.manageFields` but it was not in the k8s backend so I couldn't see the data in a good view

**Comment by knight42** [comment]
@georgettica Hi! I think this feature is good to have, I would like to implement in a few days, thanks for your advice!

**Comment by knight42** [comment]
@georgettica Hi! I have released version 0.0.7, you could try `kubectl blame -i file.yaml` to see if it works.

**Comment by georgettica** [comment]
works!
thank you ❤️

**Comment by georgettica** [comment]
PS, I used https://stackoverflow.com/q/62077977/14669675 for my testing
